services:
  external-gps:
    build:
      context: .
    ports:
      - "14560:14560/udp"
    volumes:
      - ./logs:/app/logs
    command:
      - --connect
      - udpin:0.0.0.0:14560
      - --provider
      - random-simstate
      - --static-lat
      - "55.0"
      - --static-lon
      - "37.0"
      - --static-alt
      - "180"
      - --random-radius-max
      - "300"
      - --configure-sitl-gps-input
      - --set-home
      - --critical-battery-percent
      - "10"
